directory: ~/Music/Library
library: ~/Music/beets.db
import:
  copy: no
plugins: convert mbsync inline
ignore_hidden: yes
per_disc_numbering: yes
ui:
  color: yes
  colors:
    text_highlight_minor: darkgray
import:
  resume: yes
  from_scratch: yes
musicbrainz:
  extra_tags: [year]
item_fields:
  disc_padded: u'%03i' % (disc) if disctotal > 99 else u'%02i' % (disc)
  track_padded: u'%03i' % (track) if tracktotal > 99 else u'%02i' % (track)
paths:
  default: ${album}/${disc_padded}x${track_padded}_${title}
  singleton: ${album}/${disc_padded}x${track_padded}_${title}
  comp: ${album}/${disc_padded}x${track_padded}_${title}
replace:
  '[^一-龠ぁ-ゔァ-ヴーa-zA-Z0-9々〆〤ヶ]+': _
convert:
  auto: yes
  dest: ~/Music/Archive
  never_convert_lossy_files: yes
